
export const LOCAL_WEATHER = {
    REQUEST_LOCATION_PERMISSION: 'LOCAL_WEATHER_REQUEST_LOCATION_PERMISSION',
    LOCATION_PERMISSION_SUCCESS: 'LOCAL_WEATHER_LOCATION_PERMISSION_SUCCESS',
    LOCATION_PERMISSION_FAILURE: 'LOCAL_WEATHER_LOCATION_PERMISSION_FAILURE',
    REQUEST_WEATHER_DATA:'LOCAL_WEATHER_REQUEST_WEATHER_DATA',
    REQUEST_WEATHER_DATA_SUCCESS:'LOCAL_WEATHER_REQUEST_WEATHER_DATA_SUCCESS',
    REQUEST_WEATHER_DATA_FAILURE:'LOCAL_WEATHER_REQUEST_WEATHER_DATA_FAILURE',
};